### ISSUE TITLE
Fullscreen showing topbar

### ISSUE THREAD

**Issue by boatinalamp** [GlitchMill/dotfiles#4]
fullscreen shows the polybar, this is on youtube, firefox, tiled and floated windows
![image](https://user-images.githubusercontent.com/93244703/168114469-f736dd0f-76e7-41eb-8e61-7aa904c5e4b7.png)

**Comment by GlitchMill** [comment]
This is a Xmonad Issue, This could be a possible fix -> https://hackage.haskell.org/package/xmonad-contrib-0.17.0/docs/XMonad-Hooks-EwmhDesktops.html#v:ewmhFullscreen
